apiVersion: apps/v1
kind: Deployment
metadata:
  name: autorservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autorservice
  template:
    metadata:
      labels:
        app: autorservice
    spec:
      containers:
        - name: autorservice
          image: autorservice:latest 
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: autorservice
spec:
  type: NodePort  # Expõe o serviço para acesso externo
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30001  # Porta para acessar o serviço no host
  selector:
    app: autorservice
